### ISSUE TITLE
FC stops due to --limitSjdbInsertNsj error

### ISSUE THREAD

**Issue by YanaMa** [ndaniel/fusioncatcher#67]
Hi,
I got the following error while running FusionCatcher:

Fatal LIMIT error: the number of junctions to be inserted on the fly =1364870 is larger than the limitSjdbInsertNsj=1000000
Fatal LIMIT error: the number of junctions to be inserted on the fly =1364870 is larger than the limitSjdbInsertNsj=1000000
SOLUTION: re-run with at least --limitSjdbInsertNsj 1364870

It seems like STAR is complaining here, and I'm wondering how I can increase the --limitSjdbInsertNs before running FC?
Is there a possibility that this is occurring since the samples were sequenced to an average of 89M reads?
Grateful for any input regarding this!

Best,
Yanra

**Comment by ndaniel** [comment]
@YanaMa 

Would be possible to post the exact command line parameters and inputs for the STAR command which fails?
This info can be found in end of the file `fusioncatcher.log`.

> It seems like STAR is complaining here, and I'm wondering how I can increase the --limitSjdbInsertNs before running FC?

Here I need the exact command line for STAR because STAR is executed several times by FusionCatcher.

> Is there a possibility that this is occurring since the samples were sequenced to an average of 89M reads?

I guess that the number of input reads is not that relevant. At first glance I would say that it looks like there are an exceptional large number of candidate fusion genes which FusionCatcher needs to evaluate.

The only suggestion which comes to my mind, without having any extra information, is to re-run FusionCatcher from the very beginning (that is erase the current output) using this command line `--limit-star 100000000`.

**Comment by YanaMa** [comment]
Here is a copied section from the end of the fusioncatcher.log :

--------------------------------------------------------------------------------
+-->MOCK EXECUTION (i.e. code executed outside of workflow)...
--------------------------------------------------------------------------------
==> Execution time: 0 day(s), 0 hour(s), 0 minute(s), and 0 second(s)
////////////////////////////////////////////////////////////////////////////////
  Running: step = 437   Time: 03:14   Date: 2017-09-08 (elapsed time: 0d:12h:41m)
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
==> Current working directory: '/pica/v13/b2015118_nobackup/private/RNAseq_analysis/fusion_gene_detection'

--------------------------------------------------------------------------------
+-->MOCK EXECUTION (i.e. code executed outside of workflow)...
--------------------------------------------------------------------------------
==> Execution time: 0 day(s), 0 hour(s), 0 minute(s), and 0 second(s)
////////////////////////////////////////////////////////////////////////////////
  Running: step = 438   Time: 03:14   Date: 2017-09-08 (elapsed time: 0d:12h:41m)
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
==> Current working directory: '/pica/v13/b2015118_nobackup/private/RNAseq_analysis/fusion_gene_detection'
Erasing '/scratch/11154708/results/09-259/gene-gene_split_star.fa.0.len' (size: 10 bytes)
==> Erasing file: '/scratch/11154708/results/09-259/gene-gene_split_star.fa.0.len' (size: 10 bytes)
--------------------------------------------------------------------------------
==> Execution time: 0 day(s), 0 hour(s), 0 minute(s), and 0 second(s)
////////////////////////////////////////////////////////////////////////////////
  Running: step = 439   Time: 03:14   Date: 2017-09-08 (elapsed time: 0d:12h:41m)
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
==> Current working directory: '/pica/v13/b2015118_nobackup/private/RNAseq_analysis/fusion_gene_detection'
STAR \
--genomeChrBinNbits 17 \
--genomeSAindexNbases 14 \
--runMode genomeGenerate \
--genomeSuffixLengthMax 10000 \
--runThreadN 16 \
--genomeDir /scratch/11154708/results/09-259/gene-gene_split_star.fa.0_star/ \
--genomeFastaFiles /scratch/11154708/results/09-259/gene-gene_split_star.fa.0 \
--outFileNamePrefix /scratch/11154708/results/09-259/gene-gene_split_star.fa.0_star/
--------------------------------------------------------------------------------
+-->EXECUTING...
--------------------------------------------------------------------------------
==> Execution time: 0 day(s), 0 hour(s), 9 minute(s), and 43 second(s)
////////////////////////////////////////////////////////////////////////////////
  Running: step = 440   Time: 03:24   Date: 2017-09-08 (elapsed time: 0d:12h:51m)
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
==> Current working directory: '/pica/v13/b2015118_nobackup/private/RNAseq_analysis/fusion_gene_detection'
STAR \
--twopass1readsN -1 \
--twopassMode Basic \
--genomeSAindexNbases 14 \
--sjdbOverhang 91 \
--alignIntronMax 2486488 \
--outFilterMatchNmin 16 \
--outFilterMatchNminOverLread 0.2667 \
--outFilterScoreMinOverLread 0.2667 \
--alignSplicedMateMapLminOverLmate 0.2667 \
--genomeDir /scratch/11154708/results/09-259/gene-gene_split_star.fa.0_star/ \
--runThreadN 16 \
--seedSearchStartLmax 16 \
--alignSJoverhangMin 16 \
--alignSJstitchMismatchNmax 5 -1 5 5 \
--outSJfilterOverhangMin 10 10 10 10 \
--outSJfilterCountUniqueMin 1 1 1 1 \
--outSJfilterCountTotalMin 1 1 1 1 \
--outSJfilterDistToOtherSJmin 0 0 0 0 \
--outSJfilterIntronMaxVsReadN 2486488 2486488 2486488 \
--limitOutSAMoneReadBytes 100000000 \
--scoreGapNoncan -4 \
--scoreGapATAC -4 \
--readFilesIn /scratch/11154708/results/09-259/reads_gene-gene_no-str_fixed.fq \
--outFileNamePrefix /scratch/11154708/results/09-259/gene-gene_split_star.fa.0_star-results/
--------------------------------------------------------------------------------
+-->EXECUTING...


ERROR: Workflow execution failed at step 440 while executing:
----------------
   STAR \
   --twopass1readsN -1 \
   --twopassMode Basic \
   --genomeSAindexNbases 14 \
   --sjdbOverhang 91 \
   --alignIntronMax 2486488 \
   --outFilterMatchNmin 16 \
   --outFilterMatchNminOverLread 0.2667 \
   --outFilterScoreMinOverLread 0.2667 \
   --alignSplicedMateMapLminOverLmate 0.2667 \
   --genomeDir /scratch/11154708/results/09-259/gene-gene_split_star.fa.0_star/ \
   --runThreadN 16 \
   --seedSearchStartLmax 16 \
   --alignSJoverhangMin 16 \
   --alignSJstitchMismatchNmax 5 -1 5 5 \
   --outSJfilterOverhangMin 10 10 10 10 \
   --outSJfilterCountUniqueMin 1 1 1 1 \
   --outSJfilterCountTotalMin 1 1 1 1 \
   --outSJfilterDistToOtherSJmin 0 0 0 0 \
   --outSJfilterIntronMaxVsReadN 2486488 2486488 2486488 \
   --limitOutSAMoneReadBytes 100000000 \
   --scoreGapNoncan -4 \
   --scoreGapATAC -4 \
   --readFilesIn /scratch/11154708/results/09-259/reads_gene-gene_no-str_fixed.fq \
   --outFileNamePrefix /scratch/11154708/results/09-259/gene-gene_split_star.fa.0_star-results/
----------------


Executing second time the same step/command in order to capture error messages (i.e. STDERR)...

-------------------------------------------

Fatal LIMIT error: the number of junctions to be inserted on the fly =1168238 is larger than the limitSjdbInsertNsj=1000000
Fatal LIMIT error: the number of junctions to be inserted on the fly =1168238 is larger than the limitSjdbInsertNsj=1000000
SOLUTION: re-run with at least --limitSjdbInsertNsj 1168238

Sep 08 03:36:32 ...... FATAL ERROR, exiting


################################################################################
################################################################################
TOTAL RUNNING TIME: 0 day(s), 13 hour(s), 3 minute(s), and 0 second(s)
################################################################################
################################################################################

**Comment by ndaniel** [comment]
Editing manually the Python script `bin/fusioncatcher.py` as follows might help. Afterwards just re-run FusionCatcher (using `/scratch/11154708/results/09-259/restart.sh`)

Change line number 8380 from:
```
                        job.add('--readFilesIn',outdir('reads_gene-gene_no-str_fixed.fq'),kind='input')
```
to:
```
                        job.add('--limitSjdbInsertNsj','2000000',kind='parameter')
                        job.add('--readFilesIn',outdir('reads_gene-gene_no-str_fixed.fq'),kind='input')
```
Change line number 9171 from:
```
                    job.add('--readFilesIn',outdir('reads_gene-gene_no-str_fixed.fq'),kind='input',temp_path=temp_flag)
```
to
```
                    job.add('--limitSjdbInsertNsj','2000000',kind='parameter')
                    job.add('--readFilesIn',outdir('reads_gene-gene_no-str_fixed.fq'),kind='input',temp_path=temp_flag)
```
All these can be applied by using this patch [patch.txt](https://github.com/ndaniel/fusioncatcher/files/1306099/patch.txt).

**Comment by ndaniel** [comment]
Fixed in v0.99.7d.

**Comment by YanaMa** [comment]
Hi,
Thank you for the patch. FusionCatcher ran without any problems.
/yan

**Comment by sentisci** [comment]
Hi Daniel,

I am using fusioncatcher/1.20 and still getting the same erro 

Command that I used ---> 

fusioncatcher -p ${THREADS} --limitSjdbInsertNsj=3000000 --limitOutSJcollapsed=2000000 -d /data/CCRSB/apps/pipelineSnakes/pipeline-SB/conda/envs/fusion-catcher/share/fusioncatcher-1.20/db/current/ -i Xeno_September_22_2020_1.fastq.gz,XenoP0TCP5_Xeno_September_22_2020_2.fastq.gz -o ${LOCAL}

I still get the error . From STDERR file
-------------------------------------------------------------------------
Waiting for BLAT to finish running...
BLAT finished running.
-------------------------------------------------------------------------
Joining BLAT's output files...
Done.
Fixing PSL...
Sorting PSL...
Processing PSL...
Sorting again...
The end.

Fatal LIMIT error: the number of junctions to be inserted on the fly =1324998 is larger than the limitSjdbInsertNsj=1000000
Fatal LIMIT error: the number of junctions to be inserted on the fly =1324998 is larger than the limitSjdbInsertNsj=1000000
SOLUTION: re-run with at least --limitSjdbInsertNsj 1324998

From STDOUT file
ERROR: Workflow execution failed at step 429 while executing:
----------------
   STAR \
   --runRNGseed 54321 \
   --twopass1readsN -1 \
   --twopassMode Basic \
   --genomeSAindexNbases 13 \
   --sjdbOverhang 91 \
   --alignIntronMax 1439093 \
   --outFilterMatchNmin 16 \
   --outFilterMatchNminOverLread 0.2667 \
   --outFilterScoreMinOverLread 0.2667 \
   --alignSplicedMateMapLminOverLmate 0.2667 \
   --genomeDir /lscratch/15070682/gene-gene_split_star.fa.0_star/ \
   --runThreadN 32 \
   --seedSearchStartLmax 16 \
   --alignSJoverhangMin 16 \
   --alignSJstitchMismatchNmax 5 -1 5 5 \
   --outSJfilterOverhangMin 10 10 10 10 \
   --outSJfilterCountUniqueMin 1 1 1 1 \
   --outSJfilterCountTotalMin 1 1 1 1 \
   --outSJfilterDistToOtherSJmin 0 0 0 0 \
   --outSJfilterIntronMaxVsReadN 1439093 \
    1439093 \
    1439093 \
   --limitOutSAMoneReadBytes 100000000 \
   --scoreGapNoncan -4 \
   --scoreGapATAC -4 \
   --readFilesIn /lscratch/15070682/reads_gene-gene_no-str_fixed.fq \
   --outFileNamePrefix /lscratch/15070682/gene-gene_split_star.fa.0_star-results/
----------------


Executing second time the same step/command in order to capture error messages (i.e. STDERR)...

-------------------------------------------

Fatal LIMIT error: the number of junctions to be inserted on the fly =1324998 is larger than the limitSjdbInsertNsj=1000000
 

Can you please help ?
